server:
  port: 8088
  ssl:
    key-alias: ilens_selfsigned
    key-store-password: ilens_admin
    key-store: classpath:ilens-ssl.pkcs12
    key-store-provider: SUN
    key-store-type: pkcs12
spring:
  data:
    cassandra:
      local-datacenter: datacenter1
      keyspace-name: ilens
      contact-points: localhost
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:~/.ilendbmdi
    driver-class-name: org.h2.Driver
    username: sa
    password: password
logging:
  level:
    root: info

ilens:
  api:
    protocal: https
    host: 127.0.0.1
    port: 8088
    path: api/v1/ilens/dataset
  python:
    path: python3
  user:
    train-data:
      path: /home/logicfocus/ilens/ilens-1.0/scripts/faceDetection/face_training/training_imgs

mail:
  host: smtp.gmail.com
  port: 587
  user-name: abithkumar.a@logicfocus.net
  password: mysnqilnpwlqjzfa

default-config:
  user: Admin
  password: Admin

locations:
  data-location: /home/logicfocus/ilens/snapshots
  license-location: /home/logicfocus/ilens/ilens-1.0/scripts
  json-location: /home/logicfocus/ilens/ilens-1.0/scripts
  tessearct-location: /home/logicfocus/ilens/ilens-1.0/scripts
  unknown-location: /home/logicfocus/ilens/snapshots/unknown